In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("big_dataset.csv")

In [4]:
print(df)

     PassengerId  Survived  Pclass           Name     Sex  Age  SibSp  Parch  \
0              1         0       1    Passenger_1  female    5      2      0
1              2         1       1    Passenger_2    male   33      2      2
2              3         0       3    Passenger_3    male   65      1      2
3              4         0       2    Passenger_4    male   18      3      1
4              5         0       2    Passenger_5  female   49      4      4
..           ...       ...     ...            ...     ...  ...    ...    ...
295          296         1       1  Passenger_296  female   53      0      3
296          297         1       1  Passenger_297  female   51      0      1
297          298         0       3  Passenger_298  female   39      4      3
298          299         0       3  Passenger_299    male   51      2      2
299          300         1       1  Passenger_300    male   70      1      2

       Fare Embarked
0    434.69        Q
1    481.80        Q
2     20.49        S
3    366.98        S
4    455.21        C
..      ...      ...
295  218.28        Q
296  448.87        S
297   40.28        Q
298  477.56        Q
299  329.07        S

[300 rows x 10 columns]

In [5]:
print(df.head())

   PassengerId  Survived  Pclass         Name     Sex  Age  SibSp  Parch  \
0            1         0       1  Passenger_1  female    5      2      0
1            2         1       1  Passenger_2    male   33      2      2
2            3         0       3  Passenger_3    male   65      1      2
3            4         0       2  Passenger_4    male   18      3      1
4            5         0       2  Passenger_5  female   49      4      4

     Fare Embarked
0  434.69        Q
1  481.80        Q
2   20.49        S
3  366.98        S
4  455.21        C

In [7]:
print(df.shape)

(300, 10)

In [8]:
print(df.describe)

<bound method NDFrame.describe of      PassengerId  Survived  Pclass           Name     Sex  Age  SibSp  Parch  \
0              1         0       1    Passenger_1  female    5      2      0
1              2         1       1    Passenger_2    male   33      2      2
2              3         0       3    Passenger_3    male   65      1      2
3              4         0       2    Passenger_4    male   18      3      1
4              5         0       2    Passenger_5  female   49      4      4
..           ...       ...     ...            ...     ...  ...    ...    ...
295          296         1       1  Passenger_296  female   53      0      3
296          297         1       1  Passenger_297  female   51      0      1
297          298         0       3  Passenger_298  female   39      4      3
298          299         0       3  Passenger_299    male   51      2      2
299          300         1       1  Passenger_300    male   70      1      2

       Fare Embarked
0    434.69        Q
1    481.80        Q
2     20.49        S
3    366.98        S
4    455.21        C
..      ...      ...
295  218.28        Q
296  448.87        S
297   40.28        Q
298  477.56        Q
299  329.07        S

[300 rows x 10 columns]>

In [ ]:
print(df.info)

<bound method DataFrame.info of      PassengerId  Survived  Pclass           Name     Sex  Age  SibSp  Parch  \
0              1         0       1    Passenger_1  female    5      2      0
1              2         1       1    Passenger_2    male   33      2      2
2              3         0       3    Passenger_3    male   65      1      2
3              4         0       2    Passenger_4    male   18      3      1
4              5         0       2    Passenger_5  female   49      4      4
..           ...       ...     ...            ...     ...  ...    ...    ...
295          296         1       1  Passenger_296  female   53      0      3
296          297         1       1  Passenger_297  female   51      0      1
297          298         0       3  Passenger_298  female   39      4      3
298          299         0       3  Passenger_299    male   51      2      2
299          300         1       1  Passenger_300    male   70      1      2

       Fare Embarked
0    434.69        Q
1    481.80        Q
2     20.49        S
3    366.98        S
4    455.21        C
..      ...      ...
295  218.28        Q
296  448.87        S
297   40.28        Q
298  477.56        Q
299  329.07        S

[300 rows x 10 columns]>

In [10]:
print(df.isnull)

<bound method DataFrame.isnull of      PassengerId  Survived  Pclass           Name     Sex  Age  SibSp  Parch  \
0              1         0       1    Passenger_1  female    5      2      0
1              2         1       1    Passenger_2    male   33      2      2
2              3         0       3    Passenger_3    male   65      1      2
3              4         0       2    Passenger_4    male   18      3      1
4              5         0       2    Passenger_5  female   49      4      4
..           ...       ...     ...            ...     ...  ...    ...    ...
295          296         1       1  Passenger_296  female   53      0      3
296          297         1       1  Passenger_297  female   51      0      1
297          298         0       3  Passenger_298  female   39      4      3
298          299         0       3  Passenger_299    male   51      2      2
299          300         1       1  Passenger_300    male   70      1      2

       Fare Embarked
0    434.69        Q
1    481.80        Q
2     20.49        S
3    366.98        S
4    455.21        C
..      ...      ...
295  218.28        Q
296  448.87        S
297   40.28        Q
298  477.56        Q
299  329.07        S

[300 rows x 10 columns]>

In [11]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
295,296,1,1,Passenger_296,female,53,0,3,218.28,Q
296,297,1,1,Passenger_297,female,51,0,1,448.87,S
297,298,0,3,Passenger_298,female,39,4,3,40.28,Q
298,299,0,3,Passenger_299,male,51,2,2,477.56,Q
299,300,1,1,Passenger_300,male,70,1,2,329.07,S

In [14]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Fare', 'Embarked'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  300 non-null    int64
 1   Survived     300 non-null    int64
 2   Pclass       300 non-null    int64
 3   Name         300 non-null    object
 4   Sex          300 non-null    object
 5   Age          300 non-null    int64
 6   SibSp        300 non-null    int64
 7   Parch        300 non-null    int64
 8   Fare         300 non-null    float64
 9   Embarked     300 non-null    object
dtypes: float64(1), int64(6), object(3)
memory usage: 23.6+ KB

In [16]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297    False
298    False
299    False
Length: 300, dtype: bool

In [18]:
df["Age"]

0       5
1      33
2      65
3      18
4      49
       ..
295    53
296    51
297    39
298    51
299    70
Name: Age, Length: 300, dtype: int64

In [22]:
df[["Name","Age","Sex"]]

              Name  Age     Sex
0      Passenger_1    5  female
1      Passenger_2   33    male
2      Passenger_3   65    male
3      Passenger_4   18    male
4      Passenger_5   49  female
..             ...  ...     ...
295  Passenger_296   53  female
296  Passenger_297   51  female
297  Passenger_298   39  female
298  Passenger_299   51    male
299  Passenger_300   70    male

[300 rows x 3 columns]

In [24]:
df.sort_values("Fare", ascending=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
32,33,1,3,Passenger_33,female,77,4,0,5.61,Q
165,166,0,3,Passenger_166,female,8,2,0,9.47,S
273,274,1,1,Passenger_274,male,37,1,2,12.26,S
207,208,1,2,Passenger_208,female,8,1,0,13.60,Q
230,231,1,1,Passenger_231,male,50,3,1,13.67,C
...,...,...,...,...,...,...,...,...,...,...
228,229,0,3,Passenger_229,male,33,4,2,489.42,Q
43,44,1,3,Passenger_44,male,3,3,1,492.25,Q
193,194,0,2,Passenger_194,male,36,2,0,493.41,C
139,140,0,2,Passenger_140,male,26,1,2,496.11,S
248,249,0,2,Passenger_249,female,38,4,0,496.70,S

In [25]:
df[df["Sex"] == "male"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
1,2,1,1,Passenger_2,male,33,2,2,481.80,Q
2,3,0,3,Passenger_3,male,65,1,2,20.49,S
3,4,0,2,Passenger_4,male,18,3,1,366.98,S
6,7,0,2,Passenger_7,male,26,3,3,482.44,C
8,9,0,3,Passenger_9,male,59,3,1,223.94,S
...,...,...,...,...,...,...,...,...,...,...
290,291,0,1,Passenger_291,male,15,1,4,276.96,C
291,292,0,3,Passenger_292,male,25,4,0,374.70,Q
292,293,0,2,Passenger_293,male,17,0,4,359.17,C
298,299,0,3,Passenger_299,male,51,2,2,477.56,Q
299,300,1,1,Passenger_300,male,70,1,2,329.07,S

In [26]:
df[(df["Age"] > 25) & (df["Sex"] == "female")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
4,5,0,2,Passenger_5,female,49,4,4,455.21,C
7,8,0,2,Passenger_8,female,63,2,2,381.25,C
10,11,0,3,Passenger_11,female,49,0,2,163.77,C
12,13,0,1,Passenger_13,female,33,4,3,374.19,S
20,21,1,3,Passenger_21,female,53,2,0,105.83,S
...,...,...,...,...,...,...,...,...,...,...
293,294,1,3,Passenger_294,female,66,0,4,263.01,S
294,295,1,1,Passenger_295,female,78,0,2,412.08,Q
295,296,1,1,Passenger_296,female,53,0,3,218.28,Q
296,297,1,1,Passenger_297,female,51,0,1,448.87,S
297,298,0,3,Passenger_298,female,39,4,3,40.28,Q

In [27]:
df.dropna(inplace=True)

In [28]:
df["Age"].mean()

np.float64(39.56)

In [29]:
df["Fare"].max()

496.7

In [30]:
df["Fare"].min()

5.61

In [31]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,1,Passenger_1,female,5,2,0,434.69,Q
1,2,1,1,Passenger_2,male,33,2,2,481.80,Q
2,3,0,3,Passenger_3,male,65,1,2,20.49,S
3,4,0,2,Passenger_4,male,18,3,1,366.98,S
4,5,0,2,Passenger_5,female,49,4,4,455.21,C
...,...,...,...,...,...,...,...,...,...,...
295,296,1,1,Passenger_296,female,53,0,3,218.28,Q
296,297,1,1,Passenger_297,female,51,0,1,448.87,S
297,298,0,3,Passenger_298,female,39,4,3,40.28,Q
298,299,0,3,Passenger_299,male,51,2,2,477.56,Q
299,300,1,1,Passenger_300,male,70,1,2,329.07,S

In [32]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le=LabelEncoder()

In [37]:
df["Sex"] = le.fit_transform(df["Sex"])

In [38]:
df["Embarked"] = le.fit_transform(df["Embarked"])

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,1,Passenger_1,0,5,2,0,434.69,1
1,2,1,1,Passenger_2,1,33,2,2,481.80,1
2,3,0,3,Passenger_3,1,65,1,2,20.49,2
3,4,0,2,Passenger_4,1,18,3,1,366.98,2
4,5,0,2,Passenger_5,0,49,4,4,455.21,0

In [48]:
df

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch    Fare  Embarked
0              1         0       1    0    5      2      0  434.69         1
1              2         1       1    1   33      2      2  481.80         1
2              3         0       3    1   65      1      2   20.49         2
3              4         0       2    1   18      3      1  366.98         2
4              5         0       2    0   49      4      4  455.21         0
..           ...       ...     ...  ...  ...    ...    ...     ...       ...
295          296         1       1    0   53      0      3  218.28         1
296          297         1       1    0   51      0      1  448.87         2
297          298         0       3    0   39      4      3   40.28         1
298          299         0       3    1   51      2      2  477.56         1
299          300         1       1    1   70      1      2  329.07         2

[300 rows x 9 columns]

In [49]:
X = df.drop("Survived", axis=1)

In [50]:
df

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch    Fare  Embarked
0              1         0       1    0    5      2      0  434.69         1
1              2         1       1    1   33      2      2  481.80         1
2              3         0       3    1   65      1      2   20.49         2
3              4         0       2    1   18      3      1  366.98         2
4              5         0       2    0   49      4      4  455.21         0
..           ...       ...     ...  ...  ...    ...    ...     ...       ...
295          296         1       1    0   53      0      3  218.28         1
296          297         1       1    0   51      0      1  448.87         2
297          298         0       3    0   39      4      3   40.28         1
298          299         0       3    1   51      2      2  477.56         1
299          300         1       1    1   70      1      2  329.07         2

[300 rows x 9 columns]

In [51]:
y = df["Survived"]

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

In [54]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.5

In [58]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))